# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'libraries/libqaccessibilityclient': '@latest-kf6'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
